///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String lottieNotFound = 'assets/lottie/not-found.json';
  static const String lottieNotificationEmpty = 'assets/lottie/notification_empty.json';
  static const String lottiePin = 'assets/lottie/pin.json';
  static const String lottieRefresh = 'assets/lottie/refresh.json';
  static const String lottieRestart = 'assets/lottie/restart.json';
  static const String pngAppIcon = 'assets/images/png/app_icon.png';
  static const String pngAppLogo = 'assets/images/png/app_logo.png';
  static const String pngMarker = 'assets/images/png/marker.png';
  static const String pngNoOrders = 'assets/images/png/no_orders.png';
  static const String pngNoProducts = 'assets/images/png/no_products.png';
  static const String pngSplash = 'assets/images/png/splash.png';
  static const String svgAllergy = 'assets/svg/allergy.svg';
  static const String svgAreaIcon = 'assets/svg/area-icon.svg';
  static const String svgAvatar = 'assets/svg/avatar.svg';
  static const String svgAverage = 'assets/svg/average.svg';
  static const String svgCalendar = 'assets/svg/calendar.svg';
  static const String svgCart = 'assets/svg/cart.svg';
  static const String svgCart2 = 'assets/svg/cart2.svg';
  static const String svgContact = 'assets/svg/contact.svg';
  static const String svgDelivery = 'assets/svg/delivery.svg';
  static const String svgDelivery0 = 'assets/svg/delivery0.svg';
  static const String svgDelivery2 = 'assets/svg/delivery2.svg';
  static const String svgDine = 'assets/svg/dine.svg';
  static const String svgDiscount = 'assets/svg/discount.svg';
  static const String svgDollar = 'assets/svg/dollar.svg';
  static const String svgDollarIcon = 'assets/svg/dollar_icon.svg';
  static const String svgFilePdf = 'assets/svg/filePdf.svg';
  static const String svgFilter = 'assets/svg/filter.svg';
  static const String svgHalal = 'assets/svg/halal.svg';
  static const String svgHome = 'assets/svg/home.svg';
  static const String svgHomeSvg = 'assets/svg/homeSvg.svg';
  static const String svgLikeSvg = 'assets/svg/likeSvg.svg';
  static const String svgMeat = 'assets/svg/meat.svg';
  static const String svgMenu = 'assets/svg/menu.svg';
  static const String svgNoLikeSvg = 'assets/svg/noLikeSvg.svg';
  static const String svgNoSearchSvg = 'assets/svg/noSearchSvg.svg';
  static const String svgOrderTime = 'assets/svg/orderTime.svg';
  static const String svgPickup = 'assets/svg/pickup.svg';
  static const String svgRevenue = 'assets/svg/revenue.svg';
  static const String svgSearchSvg = 'assets/svg/searchSvg.svg';
  static const String svgSectionSvgrepoCom = 'assets/svg/section-svgrepo-com.svg';
  static const String svgSelectTable = 'assets/svg/selectTable.svg';
  static const String svgStar = 'assets/svg/star.svg';
  static const String svgTable = 'assets/svg/table.svg';
  static const String svgTax = 'assets/svg/tax.svg';
  static const String svgTicket = 'assets/svg/ticket.svg';
  static const String svgUnHome = 'assets/svg/unHome.svg';
  static const String svgVegetarian = 'assets/svg/vegetarian.svg';
  static const String svgWater = 'assets/svg/water.svg';

}
