// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHvjKHsqNTcSHQ6FYnuogFTFqvv21-1WY',
    appId: '1:281710856003:web:13e17918eff83cbe6451f6',
    messagingSenderId: '281710856003',
    projectId: 'buzlinholding',
    authDomain: 'buzlinholding.firebaseapp.com',
    storageBucket: 'buzlinholding.appspot.com',
    measurementId: 'G-H7JLR5GHVR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArlaIHbpx0XUT14s2WIA3AhU4fqsks_9I',
    appId: '1:281710856003:android:b85847a030178e3d6451f6',
    messagingSenderId: '281710856003',
    projectId: 'buzlinholding',
    storageBucket: 'buzlinholding.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj1rXkOurw7_hsFCHH0Q1K1ce9cD5L0U4',
    appId: '1:281710856003:ios:b954ecf032ef2ade6451f6',
    messagingSenderId: '281710856003',
    projectId: 'buzlinholding',
    storageBucket: 'buzlinholding.appspot.com',
    androidClientId: '281710856003-3pphqa1jghckq44gikeupdos199m3at2.apps.googleusercontent.com',
    iosClientId: '281710856003-15vtp11sn8ddfoj5jmg2jncb1sobvlvl.apps.googleusercontent.com',
    iosBundleId: 'ca.buzlin.pos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj1rXkOurw7_hsFCHH0Q1K1ce9cD5L0U4',
    appId: '1:281710856003:ios:19c66850ca1f94416451f6',
    messagingSenderId: '281710856003',
    projectId: 'buzlinholding',
    storageBucket: 'buzlinholding.appspot.com',
    androidClientId: '281710856003-3pphqa1jghckq44gikeupdos199m3at2.apps.googleusercontent.com',
    iosClientId: '281710856003-6m6ks4m18m1pj2gg4v79p04ecj5gbevu.apps.googleusercontent.com',
    iosBundleId: 'org.goshops.adminDesktop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7ioq8nlduL1b5sns3usjzMY5Rr6gk1-A',
    appId: '1:281710856003:web:30e43c5eb526329f6451f6',
    messagingSenderId: '281710856003',
    projectId: 'buzlinholding',
    authDomain: 'buzlinholding.firebaseapp.com',
    storageBucket: 'buzlinholding.appspot.com',
    measurementId: 'G-3BZC0Q9YH2',
  );
}
